sudo: required
services: 
  - docker

before_install:
  - docker build -t elnino9/docker-training -f Dockerfile.dev .

script:
  - docker run -e CI=true elnino9/docker-training npm test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-React"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-804515526358"
  bucket_path: "Docker-React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: AWS_SECRET_KEY